# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUhvDtALfTrE5QbiFrPeeWc3BaCXcU1p
"""

from IPython.display import HTML

# 你可以在這裡修改考程表內容
schedule_data = """
第一節：自修, 08:25-09:10
第二節：寫作, 09:20-10:05
第三節：自修, 10:15-11:00
第四節：數學, 11:10-11:55
第五節：英文, 13:10-15:00
第六節：社會, 15:10-16:10
"""

# 設定人數
t_num = 31
p_num = 30
absent = t_num - p_num

html_code = f"""
<div id="main-container" style="background-color: #FDF5E6; padding: 30px; border-radius: 25px; font-family: sans-serif; color: #5D5D5D; min-width: 800px;">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 25px;">
        <div>
            <div id="time-label" style="font-size: 20px; font-weight: bold; color: #BC8F8F;">當 前 時 間</div>
            <div id="clock" style="font-size: 90px; font-weight: bold; color: #5D5D5D; line-height: 1;">00:00:00</div>
        </div>
        <div id="subject-box" style="background: white; padding: 20px 40px; border-radius: 20px; text-align: right; box-shadow: 2px 2px 10px rgba(0,0,0,0.05);">
            <div id="cur-subject" style="font-size: 45px; font-weight: bold; color: #BC8F8F;">休息時間</div>
            <div id="cur-range" style="font-size: 24px; color: #888;">-- : --</div>
        </div>
    </div>

    <div style="display: flex; gap: 20px;">
        <div style="background: white; padding: 25px; border-radius: 20px; flex: 1;">
            <b style="color: #BC8F8F; font-size: 22px;">📅 今日考程表</b><hr style="border: 0.5px solid #FDF5E6;">
            <div id="schedule-list"></div>
        </div>
        <div style="background: white; padding: 25px; border-radius: 20px; flex: 1.5; text-align: center;">
            <b style="color: #BC8F8F; letter-spacing: 10px; font-size: 20px;">考 場 規 範</b>
            <h1 style="font-size: 48px; margin: 30px 0;">🚫 考完請在位靜候<br><span style="font-size: 32px; color: #666;">等監考老師收完卷</span></h1>
            <div style="display: flex; justify-content: space-around; background: #FDF5E6; padding: 20px; border-radius: 15px;">
                <div><small>應到</small><br><b style="font-size: 45px;">{t_num}</b></div>
                <div><small>實到</small><br><b style="font-size: 45px;">{p_num}</b></div>
                <div><small style="color: {("#E63946" if absent > 0 else "#5D5D5D")}">缺席</small><br><b style="font-size: 45px; color: {("#E63946" if absent > 0 else "#5D5D5D")};">{absent}</b></div>
            </div>
        </div>
    </div>
</div>

<script>
const rawSchedule = `{schedule_data}`;
const sch = rawSchedule.trim().split('\\n').map(line => {{
    const [n, t] = line.split(',');
    const [s, e] = t.trim().split('-');
    return {{ n: n.trim(), s: s.trim(), e: e.trim() }};
}});

function update() {{
    const now = new Date();
    const h = String(now.getHours()).padStart(2, '0');
    const m = String(now.getMinutes()).padStart(2, '0');
    const s = String(now.getSeconds()).padStart(2, '0');
    const hm = h + ":" + m;

    document.getElementById('clock').innerText = h + ":" + m + ":" + s;

    let cur = "休息時間", rng = "-- : --", hiIdx = -1, isUrgent = false;

    sch.forEach((x, i) => {{
        if (hm >= x.s && hm <= x.e) {{
            cur = x.n; rng = x.s + " - " + x.e; hiIdx = i;
            const endParts = x.e.split(':');
            const endTime = new Date();
            endTime.setHours(parseInt(endParts[0]), parseInt(endParts[1]), 0);
            const diff = (endTime - now) / 1000 / 60;
            if (diff > 0 && diff <= 10) isUrgent = true;
        }}
    }});

    // 更新顏色與內容
    const warnRed = "#E63946";
    const themeBrown = "#BC8F8F";
    const clock = document.getElementById('clock');
    const label = document.getElementById('time-label');
    const box = document.getElementById('subject-box');
    const subj = document.getElementById('cur-subject');

    clock.style.color = isUrgent ? warnRed : "#5D5D5D";
    label.innerText = isUrgent ? "⚠️ 考試即將結束" : "當 前 時 間";
    label.style.color = isUrgent ? warnRed : themeBrown;
    box.style.border = isUrgent ? "4px solid " + warnRed : "none";
    subj.innerText = cur;
    subj.style.color = isUrgent ? warnRed : themeBrown;
    document.getElementById('cur-range').innerText = rng;

    // 渲染列表
    let listHtml = "";
    sch.forEach((x, i) => {{
        const isHi = i === hiIdx;
        listHtml += `<div style="background: ${{isHi ? '#A3B18A' : 'transparent'}}; color: ${{isHi ? 'white' : '#555'}}; border-radius: 10px; padding: 12px; display: flex; justify-content: space-between; font-size: 18px; margin-top: 5px; border-bottom: ${{isHi ? 'none' : '1px solid #eee'}};">
            <span>${{x.n}}</span><span>${{x.s}} - ${{x.e}}</span>
        </div>`;
    }});
    document.getElementById('schedule-list').innerHTML = listHtml;
}}

setInterval(update, 1000);
update();
</script>
"""

display(HTML(html_code))